local ffi = require 'ffi'
-- 确保加载了包含常量的绑定文件
require 'ffi.req' 'Windows.sdk.winioctl'

local M = {}
local C = ffi.C

-- 映射 FFI 常量到 Lua 表，方便调用
M.IOCTL = {
    GET_LAYOUT = C.IOCTL_DISK_GET_DRIVE_LAYOUT_EX,
    SET_LAYOUT = C.IOCTL_DISK_SET_DRIVE_LAYOUT_EX,
    GET_GEO = C.IOCTL_DISK_GET_DRIVE_GEOMETRY_EX,
    UPDATE = C.IOCTL_DISK_UPDATE_PROPERTIES,
    CREATE = C.IOCTL_DISK_CREATE_DISK,
    GET_NUM = C.IOCTL_STORAGE_GET_DEVICE_NUMBER,
    QUERY_PROP = C.IOCTL_STORAGE_QUERY_PROPERTY,
    
    -- Volume Control
    LOCK = C.FSCTL_LOCK_VOLUME,
    UNLOCK = C.FSCTL_UNLOCK_VOLUME,
    DISMOUNT = C.FSCTL_DISMOUNT_VOLUME,
    DASD = C.FSCTL_ALLOW_EXTENDED_DASD_IO,
    
    -- [RESTORED] Resize Ops
    EXTEND = C.FSCTL_EXTEND_VOLUME,
    SHRINK = C.FSCTL_SHRINK_VOLUME,
    
    GET_ATTRIBUTES = C.IOCTL_DISK_GET_DISK_ATTRIBUTES,
    SET_ATTRIBUTES = C.IOCTL_DISK_SET_DISK_ATTRIBUTES,
    GET_VOL_EXTENTS = C.VOLUME_GET_VOLUME_DISK_EXTENTS,
    USB_HUB_CYCLE_PORT = C.IOCTL_USB_HUB_CYCLE_PORT
}

M.DISK_ATTRIBUTE = { OFFLINE = 1, READ_ONLY = 2 }

return M