local ffi = require 'ffi'
local winioctl = require 'ffi.req' 'Windows.sdk.winioctl'
local M = {}
M.IOCTL = {
    GET_LAYOUT = winioctl.C.IOCTL_DISK_GET_DRIVE_LAYOUT_EX,
    SET_LAYOUT = winioctl.C.IOCTL_DISK_SET_DRIVE_LAYOUT_EX,
    GET_GEO = winioctl.C.IOCTL_DISK_GET_DRIVE_GEOMETRY_EX,
    UPDATE = winioctl.C.IOCTL_DISK_UPDATE_PROPERTIES,
    CREATE = winioctl.C.IOCTL_DISK_CREATE_DISK,
    GET_NUM = winioctl.C.IOCTL_STORAGE_GET_DEVICE_NUMBER,
    QUERY_PROP = winioctl.C.IOCTL_STORAGE_QUERY_PROPERTY,
    LOCK = winioctl.C.FSCTL_LOCK_VOLUME,
    UNLOCK = winioctl.C.FSCTL_UNLOCK_VOLUME,
    DISMOUNT = winioctl.C.FSCTL_DISMOUNT_VOLUME,
    DASD = winioctl.C.FSCTL_ALLOW_EXTENDED_DASD_IO,
    GET_ATTRIBUTES = winioctl.C.IOCTL_DISK_GET_DISK_ATTRIBUTES,
    SET_ATTRIBUTES = winioctl.C.IOCTL_DISK_SET_DISK_ATTRIBUTES,
    GET_VOL_EXTENTS = winioctl.C.VOLUME_GET_VOLUME_DISK_EXTENTS
}
M.DISK_ATTRIBUTE = { OFFLINE = 1, READ_ONLY = 2 }
return M