local ffi = require 'ffi'
-- 确保加载了包含常量的绑定文件
require 'ffi.req' 'Windows.sdk.winioctl'

local M = {}
-- 映射 FFI 常量到 Lua 表，方便调用
M.IOCTL = {
    GET_LAYOUT = ffi.C.IOCTL_DISK_GET_DRIVE_LAYOUT_EX,
    SET_LAYOUT = ffi.C.IOCTL_DISK_SET_DRIVE_LAYOUT_EX,
    GET_GEO = ffi.C.IOCTL_DISK_GET_DRIVE_GEOMETRY_EX,
    UPDATE = ffi.C.IOCTL_DISK_UPDATE_PROPERTIES,
    CREATE = ffi.C.IOCTL_DISK_CREATE_DISK,
    GET_NUM = ffi.C.IOCTL_STORAGE_GET_DEVICE_NUMBER,
    QUERY_PROP = ffi.C.IOCTL_STORAGE_QUERY_PROPERTY,
    LOCK = ffi.C.FSCTL_LOCK_VOLUME,
    UNLOCK = ffi.C.FSCTL_UNLOCK_VOLUME,
    DISMOUNT = ffi.C.FSCTL_DISMOUNT_VOLUME,
    DASD = ffi.C.FSCTL_ALLOW_EXTENDED_DASD_IO,
    GET_ATTRIBUTES = ffi.C.IOCTL_DISK_GET_DISK_ATTRIBUTES,
    SET_ATTRIBUTES = ffi.C.IOCTL_DISK_SET_DISK_ATTRIBUTES,
    GET_VOL_EXTENTS = ffi.C.VOLUME_GET_VOLUME_DISK_EXTENTS,
    USB_HUB_CYCLE_PORT = ffi.C.IOCTL_USB_HUB_CYCLE_PORT
}
M.DISK_ATTRIBUTE = { OFFLINE = 1, READ_ONLY = 2 }
return M